version: '3'

tasks:
  default:
    cmds:
      - task: validate

  setup:
    desc: Install dependencies
    cmds:
      - go mod download
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  build:
    desc: Build the code
    cmds:
      - go build ./...

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  validate:
    desc: Verify the project (lint, test, build)
    cmds:
      - task: lint
      - task: test
      - task: build
